In [1]:
import numpy as np

In [3]:
A = np.array([[3, 1], [1, 3]])

In [4]:
A

array([[3, 1],
       [1, 3]])

In [5]:
U, S, V_t = np.linalg.svd(A)

In [6]:
U

array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]])

In [8]:
S

array([4., 2.])

In [10]:
V_t

array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]])

array([[False, False],
       [False,  True]])