In [2]:
import tensorflow as tf
print(f"The version of Tensorflow is: {tf.__version__}")

The version of Tensorflow is: 2.18.0


In [3]:
# Rank - 0 tensor
t1 = tf.constant(1)
print(t1)

tf.Tensor(1, shape=(), dtype=int32)


In [4]:
# Rank - 1 tesnor
t2 = tf.constant([1, 4, 12])
print(t2)

tf.Tensor([ 1  4 12], shape=(3,), dtype=int32)


In [5]:
# Rank-2 tensor
t3 = tf.constant([
    [1, 2],
    [3, 4],
    [5, 6]
])

print(t3)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [6]:
# Rank-3 Tensor

t4 = tf.constant([
        [[1, 2, 3, 4, 5],
        [0.1, 0.2, 0.3, 0.4, 0.5]],
        [[11, 12, 13, 14, 15],
        [0.11, 0.12, .13, .14, 0.15]],
        [[111, 112, 113, 114, 115],
        [0.21, 0.22, .23, .24, 0.25]]
    ], dtype="float64")

print(t4)

tf.Tensor(
[[[1.00e+00 2.00e+00 3.00e+00 4.00e+00 5.00e+00]
  [1.00e-01 2.00e-01 3.00e-01 4.00e-01 5.00e-01]]

 [[1.10e+01 1.20e+01 1.30e+01 1.40e+01 1.50e+01]
  [1.10e-01 1.20e-01 1.30e-01 1.40e-01 1.50e-01]]

 [[1.11e+02 1.12e+02 1.13e+02 1.14e+02 1.15e+02]
  [2.10e-01 2.20e-01 2.30e-01 2.40e-01 2.50e-01]]], shape=(3, 2, 5), dtype=float64)


## Types of tensors 
1. Constant Tensors


### 1. Constant Tensors 

In [17]:
# Zero dimension tensor
tensor_0 = tf.constant(1, name="zeroDim")
print(tensor_0)


tf.Tensor(1, shape=(), dtype=int32)


In [21]:
# One dimensional Tensor
tensor_1 = tf.constant(["Shoyeb", "Durgesh", "Prakhar"])
print(tensor_1)

tf.Tensor([b'Shoyeb' b'Durgesh' b'Prakhar'], shape=(3,), dtype=string)


In [28]:
tf.shape(t4), tf.shape(t4)

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 2, 5])>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 2, 5])>)

In [30]:
tf.print(t4)

[[[1 2 3 4 5]
  [0.1 0.2 0.3 0.4 0.5]]

 [[11 12 13 14 15]
  [0.11 0.12 0.13 0.14 0.15]]

 [[111 112 113 114 115]
  [0.21 0.22 0.23 0.24 0.25]]]
