In [1]:
import tensorflow as tf

In [6]:
x = tf.constant([1, 2 , 3, 4, 5, 6])

In [7]:
x.shape

TensorShape([6])

In [18]:
# Reshape the structre of the tensor
print(tf.reshape(x, (3, 2)))
x = tf.reshape(x, (2, 3))
print(x)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [20]:
# Flatten the tensor
print("tesnor x\n", x, sep="")
tf.reshape(x, (x.shape[0] * x.shape[1]))

tesnor x
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6])>

In [22]:
y = tf.constant([
    [[[1], [2]], [[3], [4]]],
    [[[5], [6]], [[7], [8]]]
])
y

<tf.Tensor: shape=(2, 2, 2, 1), dtype=int32, numpy=
array([[[[1],
         [2]],

        [[3],
         [4]]],


       [[[5],
         [6]],

        [[7],
         [8]]]])>

In [25]:
# We can also pass (-1) to reshape 
tf.reshape(y, (-1))

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8])>

In [28]:
z = tf.constant([
    [1, 2, 3, 4],
    [6, 7, 8, 9]
])
z

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [6, 7, 8, 9]])>

In [35]:
print(tf.reshape(z, (8, -1)))
print(tf.reshape(z, (2, -1)))
print(tf.reshape(z, (4, -1)))

tf.Tensor(
[[1]
 [2]
 [3]
 [4]
 [6]
 [7]
 [8]
 [9]], shape=(8, 1), dtype=int32)
tf.Tensor(
[[1 2 3 4]
 [6 7 8 9]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]
 [6 7]
 [8 9]], shape=(4, 2), dtype=int32)


In [40]:
x = tf.constant([1, 2, 3, 4, 5, 6, 7, 8])
tf.reshape(x, (4, -1, 2))
tf.reshape(x, (2, -1, 2))

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])>