In [1]:
import tensorflow as tf

In [2]:
x = tf.constant([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ]
])

In [3]:
x

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])>

In [13]:
tf.slice(x, [0, 1, 0], [1, 2, 2])

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[4, 5],
        [7, 8]]])>

In [15]:
tf.slice(x, [0, 1, 0], [2, 1, 2])

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[ 4,  5]],

       [[13, 14]]])>

In [16]:
tf.slice(x, [0, 1, 0], [2, 2, 3])  # <or> 

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 4,  5,  6],
        [ 7,  8,  9]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [18]:
tf.slice(x, [0, 1, 0], [-1, -1, -1]) # Select all remaining elements

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 4,  5,  6],
        [ 7,  8,  9]],

       [[13, 14, 15],
        [16, 17, 18]]])>