In [1]:
import tensorflow as tf

## Extract contiguosly from tensor

In [2]:
x = tf.constant([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ]
])

In [3]:
x

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])>

In [13]:
tf.slice(x, [0, 1, 0], [1, 2, 2])

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[4, 5],
        [7, 8]]])>

In [15]:
tf.slice(x, [0, 1, 0], [2, 1, 2])

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[ 4,  5]],

       [[13, 14]]])>

In [16]:
tf.slice(x, [0, 1, 0], [2, 2, 3])  # <or> 

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 4,  5,  6],
        [ 7,  8,  9]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [18]:
tf.slice(x, [0, 1, 0], [-1, -1, -1]) # Select all remaining elements

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 4,  5,  6],
        [ 7,  8,  9]],

       [[13, 14, 15],
        [16, 17, 18]]])>

## Extract non-contiguosly from tensor

In [24]:
x = tf.constant([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
tf.gather(x, [3, 7])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 8])>

In [30]:
tf.gather(x, [[0, 7], [1, 6], [2, 5], [5, 5]])

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 8],
       [2, 7],
       [3, 6],
       [6, 6]])>

In [37]:
x = tf.constant([
    [10, 11, 12],
    [13, 14, 15],
    [16, 17, 18]
])
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])>

In [38]:
tf.gather(x, indices = [1])  # 1st row from 0th index

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[13, 14, 15]])>

In [39]:
tf.gather(x, indices = [1, 0])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[13, 14, 15],
       [10, 11, 12]])>

In [ ]:
y = tf.gather(x, indices = [0], axis = 0)  # axis = 0, for row
z = tf.gather(y, indices = [0], axis = 1)  # axis = 1, for columns
z

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[10]])>

In [49]:
x = tf.constant([1, 2, 3, 4, 5, 6, 8])
tf.gather(x, indices = [[1, 6], [0, 3]]).numpy()

array([[2, 8],
       [1, 4]])

In [52]:
tf_3 = tf.constant([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ]
])
tf_3

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])>

InvalidArgumentError: {{function_node __wrapped__GatherV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} indices[1,0] = 2 is not in [0, 1) [Op:GatherV2]